"""Implementation of statechart lock_controller.
Generated by itemis CREATE code generator.
"""

import queue
import sys, os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../lib')))
from yakindu.rx import Observable

class LockController:
	"""Implementation of the state machine LockController.
	"""

	class State:
		""" State Enum
		"""
		(
			main_region_controller,
			main_region_controller_water_controller_idle,
			main_region_controller_traffic_door_controller_temp,
			null_state
		) = range(4)
	
	
	def __init__(self):
		""" Declares all necessary variables including list of states, histories etc. 
		"""
		
		self.LOW = 0
		self.HIGH = 1
		self.LOW_LVL = 500
		self.HIGH_LVL = 1500
		self.request_lvl_change = None
		self.water_lvl = None
		self.water_lvl_value = None
		self.resume = None
		self.door_obstructed = None
		self.set_request_pending = None
		self.set_request_pending_value = None
		self.set_request_pending_observable = Observable()
		self.set_sensor_broken = None
		self.set_sensor_broken_observable = Observable()
		self.open_flow = None
		self.open_flow_value = None
		self.open_flow_observable = Observable()
		self.close_flow = None
		self.close_flow_value = None
		self.close_flow_observable = Observable()
		self.open_doors = None
		self.open_doors_value = None
		self.open_doors_observable = Observable()
		self.close_doors = None
		self.close_doors_value = None
		self.close_doors_observable = Observable()
		self.green_light = None
		self.green_light_value = None
		self.green_light_observable = Observable()
		self.red_light = None
		self.red_light_value = None
		self.red_light_observable = Observable()
		
		self.in_event_queue = queue.Queue()
		
		# enumeration of all states:
		self.__State = LockController.State
		self.__state_conf_vector_changed = None
		self.__state_vector = [None] * 2
		for __state_index in range(2):
			self.__state_vector[__state_index] = self.State.null_state
		
		# initializations:
		self.__is_executing = False
		self.__state_conf_vector_position = None
	
	def is_active(self):
		"""Checks if the state machine is active.
		"""
		return self.__state_vector[0] is not self.__State.null_state or self.__state_vector[1] is not self.__State.null_state
	
	def is_final(self):
		"""Checks if the statemachine is final.
		Always returns 'false' since this state machine can never become final.
		"""
		return False
			
	def is_state_active(self, state):
		"""Checks if the state is currently active.
		"""
		s = state
		if s == self.__State.main_region_controller:
			return (self.__state_vector[0] >= self.__State.main_region_controller)\
				and (self.__state_vector[0] <= self.__State.main_region_controller_traffic_door_controller_temp)
		if s == self.__State.main_region_controller_water_controller_idle:
			return self.__state_vector[0] == self.__State.main_region_controller_water_controller_idle
		if s == self.__State.main_region_controller_traffic_door_controller_temp:
			return self.__state_vector[1] == self.__State.main_region_controller_traffic_door_controller_temp
		return False
		
	def __execute_queued_event(self, func):
		func()
	
	def __get_next_event(self):
		if not self.in_event_queue.empty():
			return self.in_event_queue.get()
		return None
	
	
	def raise_request_lvl_change(self):
		"""Raise method for event request_lvl_change.
		"""
		self.in_event_queue.put(self.__raise_request_lvl_change_call)
		self.run_cycle()
	
	def __raise_request_lvl_change_call(self):
		"""Raise callback for event request_lvl_change.
		"""
		self.request_lvl_change = True
	
	def raise_water_lvl(self, value):
		"""Raise method for event water_lvl.
		"""
		self.in_event_queue.put(lambda: self.__raise_water_lvl_call(value))
		self.run_cycle()
	
	def __raise_water_lvl_call(self, value):
		"""Raise callback for event water_lvl.
		"""
		self.water_lvl = True
		self.water_lvl_value = value
	
	def raise_resume(self):
		"""Raise method for event resume.
		"""
		self.in_event_queue.put(self.__raise_resume_call)
		self.run_cycle()
	
	def __raise_resume_call(self):
		"""Raise callback for event resume.
		"""
		self.resume = True
	
	def raise_door_obstructed(self):
		"""Raise method for event door_obstructed.
		"""
		self.in_event_queue.put(self.__raise_door_obstructed_call)
		self.run_cycle()
	
	def __raise_door_obstructed_call(self):
		"""Raise callback for event door_obstructed.
		"""
		self.door_obstructed = True
	
	def __enter_sequence_main_region_controller_default(self):
		"""'default' enter sequence for state Controller.
		"""
		#'default' enter sequence for state Controller
		self.__enter_sequence_main_region_controller_water_controller_default()
		self.__enter_sequence_main_region_controller_traffic_door_controller_default()
		
	def __enter_sequence_main_region_controller_water_controller_idle_default(self):
		"""'default' enter sequence for state Idle.
		"""
		#'default' enter sequence for state Idle
		self.__state_vector[0] = self.State.main_region_controller_water_controller_idle
		self.__state_conf_vector_position = 0
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_controller_traffic_door_controller_temp_default(self):
		"""'default' enter sequence for state temp.
		"""
		#'default' enter sequence for state temp
		self.__state_vector[1] = self.State.main_region_controller_traffic_door_controller_temp
		self.__state_conf_vector_position = 1
		self.__state_conf_vector_changed = True
		
	def __enter_sequence_main_region_default(self):
		"""'default' enter sequence for region main region.
		"""
		#'default' enter sequence for region main region
		self.__react_main_region__entry_default()
		
	def __enter_sequence_main_region_controller_water_controller_default(self):
		"""'default' enter sequence for region WaterController.
		"""
		#'default' enter sequence for region WaterController
		self.__react_main_region_controller_water_controller__entry_default()
		
	def __enter_sequence_main_region_controller_traffic_door_controller_default(self):
		"""'default' enter sequence for region TrafficDoorController.
		"""
		#'default' enter sequence for region TrafficDoorController
		self.__react_main_region_controller_traffic_door_controller__entry_default()
		
	def __exit_sequence_main_region_controller_water_controller_idle(self):
		"""Default exit sequence for state Idle.
		"""
		#Default exit sequence for state Idle
		self.__state_vector[0] = self.State.main_region_controller
		self.__state_conf_vector_position = 0
		
	def __exit_sequence_main_region_controller_traffic_door_controller_temp(self):
		"""Default exit sequence for state temp.
		"""
		#Default exit sequence for state temp
		self.__state_vector[1] = self.State.main_region_controller
		self.__state_conf_vector_position = 1
		
	def __exit_sequence_main_region(self):
		"""Default exit sequence for region main region.
		"""
		#Default exit sequence for region main region
		state = self.__state_vector[0]
		if state == self.State.main_region_controller_water_controller_idle:
			self.__exit_sequence_main_region_controller_water_controller_idle()
		state = self.__state_vector[1]
		if state == self.State.main_region_controller_traffic_door_controller_temp:
			self.__exit_sequence_main_region_controller_traffic_door_controller_temp()
		
	def __react_main_region_controller_water_controller__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_main_region_controller_water_controller_idle_default()
		
	def __react_main_region_controller_traffic_door_controller__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_main_region_controller_traffic_door_controller_temp_default()
		
	def __react_main_region__entry_default(self):
		"""Default react sequence for initial entry .
		"""
		#Default react sequence for initial entry 
		self.__enter_sequence_main_region_controller_default()
		
	def __react(self, transitioned_before):
		"""Implementation of __react function.
		"""
		#State machine reactions.
		return transitioned_before
	
	
	def __main_region_controller_react(self, transitioned_before):
		"""Implementation of __main_region_controller_react function.
		"""
		#The reactions of state Controller.
		return self.__react(transitioned_before)
	
	
	def __main_region_controller_water_controller_idle_react(self, transitioned_before):
		"""Implementation of __main_region_controller_water_controller_idle_react function.
		"""
		#The reactions of state Idle.
		return self.__main_region_controller_react(transitioned_before)
	
	
	def __main_region_controller_traffic_door_controller_temp_react(self, transitioned_before):
		"""Implementation of __main_region_controller_traffic_door_controller_temp_react function.
		"""
		#The reactions of state temp.
		return transitioned_before
	
	
	def __clear_in_events(self):
		"""Implementation of __clear_in_events function.
		"""
		self.request_lvl_change = False
		self.water_lvl = False
		self.resume = False
		self.door_obstructed = False
	
	
	def __micro_step(self):
		"""Implementation of __micro_step function.
		"""
		transitioned = -1
		self.__state_conf_vector_position = 0
		state = self.__state_vector[0]
		if state == self.State.main_region_controller_water_controller_idle:
			transitioned = self.__main_region_controller_water_controller_idle_react(transitioned)
		if self.__state_conf_vector_position < 1:
			state = self.__state_vector[1]
			if state == self.State.main_region_controller_traffic_door_controller_temp:
				self.__main_region_controller_traffic_door_controller_temp_react(transitioned)
	
	
	def run_cycle(self):
		"""Implementation of run_cycle function.
		"""
		#Performs a 'run to completion' step.
		if self.__is_executing:
			return
		self.__is_executing = True
		next_event = self.__get_next_event()
		if next_event is not None:
			self.__execute_queued_event(next_event)
		condition_0 = True
		while condition_0:
			self.__micro_step()
			self.__clear_in_events()
			condition_0 = False
			next_event = self.__get_next_event()
			if next_event is not None:
				self.__execute_queued_event(next_event)
				condition_0 = True
		self.__is_executing = False
	
	
	def enter(self):
		"""Implementation of enter function.
		"""
		#Activates the state machine.
		if self.__is_executing:
			return
		self.__is_executing = True
		#Default enter sequence for statechart LockController
		self.__enter_sequence_main_region_default()
		self.__is_executing = False
	
	
	def exit(self):
		"""Implementation of exit function.
		"""
		#Deactivates the state machine.
		if self.__is_executing:
			return
		self.__is_executing = True
		#Default exit sequence for statechart LockController
		self.__exit_sequence_main_region()
		self.__state_vector[0] = self.State.null_state
		self.__state_vector[1] = self.State.null_state
		self.__state_conf_vector_position = 1
		self.__is_executing = False
	
	
	def trigger_without_event(self):
		"""Implementation of triggerWithoutEvent function.
		"""
		self.run_cycle()
	
